"""Train a release-contract candidate scorer from self-play Q rollouts.

This is a research-only learner for the JSONL emitted by
``tools/generate_selfplay.py``.  Every labelled candidate is a forced-action
continuation from the same deal and receives a fixed-policy terminal team
margin.  The learner ranks larger margins above smaller margins, regresses a
normalised margin, and retains a small selected-action cross-entropy anchor.

The output uses the existing :class:`CandidateModel` unchanged, so a future
checkpoint can be parity/export tested without a feature or C++ contract
change.  The generator's labels are policy-evaluation targets, not exact
optimal Q values; no checkpoint from this script is a release candidate until
the usual paired official evaluation passes.
"""
from __future__ import annotations

import argparse
from contextlib import nullcontext
from dataclasses import asdict
import hashlib
import json
import math
from pathlib import Path
import random
import time

import numpy as np
import torch
import torch.nn.functional as F

from model import CandidateModel, ModelConfig
from features import FEATURE_VERSION
from train_bc import sha256_file


SCHEMA = "oxbot-selfplay-candidate-v1"
RULES_CONTRACT = "botzone-corrected-fa63589d-v1"
# The ABI/rules contract above is shared by the C++ feature exporter.  Rollout
# labels also bind to the exact referee bytes, so attachment-era data cannot be
# silently mixed with data generated by the corrected official judge.
OFFICIAL_JUDGE_SHA256 = "910cba94244106b68535b8bee67631b476241a9924bd1789dacbbf217fb1e895"
LEGACY_ATTACHMENT_JUDGE_SHA256 = "fa63589d3f69ce9127093cec417f1635d8cc17205d80e70f03e44bc6809fc622"
OFFICIAL_ROLLOUT_RULES_CONTRACT = "botzone-official-910cba94-v1"
LEGACY_ROLLOUT_RULES_CONTRACT = "botzone-attachment-fa63589d-v1"
EXPERIMENT_SCHEMA = "oxbot-rollout-q-training-v1"


def atomic_json(path: Path, payload: dict) -> None:
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temp.replace(path)


def _finite_vector(value, size, name):
    if not isinstance(value, list) or len(value) != size:
        raise ValueError(f"{name} must have length {size}")
    result = np.asarray(value, dtype=np.float32)
    if not np.isfinite(result).all():
        raise ValueError(f"{name} contains nonfinite values")
    return result


def _row_key(row: dict) -> tuple[int, int, int, int]:
    # ``game_index`` restarts at zero for each generator invocation; include
    # the game seed so separately generated train/validation files cannot
    # collide merely because both contain their first game.
    values = (row.get("game_seed"), row.get("game_index"), row.get("seat"), row.get("event_index"))
    if any(type(value) is not int for value in values):
        raise ValueError("self-play row identity is missing or non-integer")
    return values


def report_rollout_identity(report_path: Path) -> tuple[str, str, dict]:
    """Read and classify generator provenance, failing closed on unknown judges.

    Reports written before the explicit ``rollout_rules_contract`` field are
    still readable when their oracle SHA is one of the two known identities.
    The caller must keep the resulting identity pair identical for train and
    validation, so legacy attachment labels can never be mixed with official
    labels.
    """
    if not report_path.is_file():
        raise ValueError(f"generator provenance report is missing: {report_path}")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    if (report.get("schema") != SCHEMA or report.get("status") != "complete"
            or report.get("feature_version") != FEATURE_VERSION
            or report.get("rules_contract") != RULES_CONTRACT
            or report.get("test_used") is not False):
        raise ValueError(f"{report_path}: invalid generator provenance")
    oracle_sha = report.get("oracle_sha256")
    if not isinstance(oracle_sha, str):
        raise ValueError(f"{report_path}: oracle_sha256 is missing")
    configured = report.get("rollout_rules_contract")
    if configured is None:
        # Legacy reports predate the explicit field; classify only known bytes.
        if oracle_sha == OFFICIAL_JUDGE_SHA256:
            configured = OFFICIAL_ROLLOUT_RULES_CONTRACT
        elif oracle_sha == LEGACY_ATTACHMENT_JUDGE_SHA256:
            configured = LEGACY_ROLLOUT_RULES_CONTRACT
        else:
            raise ValueError(f"{report_path}: unknown legacy oracle SHA256")
    expected_contract = (OFFICIAL_ROLLOUT_RULES_CONTRACT if oracle_sha == OFFICIAL_JUDGE_SHA256
                         else LEGACY_ROLLOUT_RULES_CONTRACT if oracle_sha == LEGACY_ATTACHMENT_JUDGE_SHA256
                         else None)
    if expected_contract is None or configured != expected_contract:
        raise ValueError(f"{report_path}: rollout_rules_contract/oracle_sha256 mismatch")
    return configured, oracle_sha, report


def load_rollouts(path: Path, report_path: Path,
                  expected_identity: tuple[str, str] | None = None) -> list[dict]:
    """Load and validate one generator JSONL without accepting hidden fields."""
    rollout_contract, oracle_sha, report = report_rollout_identity(report_path)
    if expected_identity is not None and (rollout_contract, oracle_sha) != expected_identity:
        raise ValueError(f"{report_path}: train/validation rollout identities differ")
    expected_sha = report.get("output_sha256")
    if not isinstance(expected_sha, str) or sha256_file(path) != expected_sha:
        raise ValueError(f"{path}: JSONL SHA256 differs from generator report")
    rows = []
    seen = set()
    with path.open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            if not isinstance(row, dict) or row.get("schema") != SCHEMA:
                raise ValueError(f"{path}:{line_number}: unexpected self-play schema")
            if row.get("stage") != "play" or row.get("feature_version", FEATURE_VERSION) != FEATURE_VERSION:
                raise ValueError(f"{path}:{line_number}: row is not a play/feature-v1 record")
            row_contract = row.get("rollout_rules_contract")
            row_oracle = row.get("oracle_sha256")
            if row_contract is not None or row_oracle is not None:
                if row_contract != rollout_contract or row_oracle != oracle_sha:
                    raise ValueError(f"{path}:{line_number}: row/report rollout identity differs")
            elif rollout_contract == OFFICIAL_ROLLOUT_RULES_CONTRACT:
                raise ValueError(f"{path}:{line_number}: official rollout row lacks provenance fields")
            key = _row_key(row)
            if key in seen:
                raise ValueError(f"{path}:{line_number}: duplicate row identity {key}")
            seen.add(key)
            state = _finite_vector(row.get("state"), 128, "state")
            raw_tokens = row.get("tokens")
            if not isinstance(raw_tokens, list) or not 2 <= len(raw_tokens) <= 256:
                raise ValueError(f"{path}:{line_number}: invalid token window")
            if any(type(value) is not int or not 0 < value < 128 for value in raw_tokens):
                raise ValueError(f"{path}:{line_number}: token outside 1..127")
            moves = row.get("moves")
            actions = row.get("actions")
            if not isinstance(moves, list) or not moves or not isinstance(actions, list) or len(actions) != len(moves):
                raise ValueError(f"{path}:{line_number}: candidate arrays are malformed")
            action_array = np.asarray(actions, dtype=np.float32)
            if action_array.shape != (len(moves), 128) or not np.isfinite(action_array).all():
                raise ValueError(f"{path}:{line_number}: action feature shape/nonfinite value")
            selected = row.get("selected")
            if type(selected) is not int or not 0 <= selected < len(moves):
                raise ValueError(f"{path}:{line_number}: selected index is invalid")
            candidate_q = row.get("candidate_q")
            if not isinstance(candidate_q, dict) or not candidate_q:
                raise ValueError(f"{path}:{line_number}: candidate_q labels are missing")
            labels = {}
            for raw_index, target in candidate_q.items():
                try:
                    index = int(raw_index)
                except (TypeError, ValueError) as exc:
                    raise ValueError(f"{path}:{line_number}: candidate_q index is not integer") from exc
                if not 0 <= index < len(moves) or index in labels or not isinstance(target, dict):
                    raise ValueError(f"{path}:{line_number}: candidate_q index is out of range/duplicate")
                margin = target.get("team_margin")
                team_win = target.get("team_win")
                if type(margin) is not int or margin < -3 or margin > 3:
                    raise ValueError(f"{path}:{line_number}: invalid candidate team margin")
                if type(team_win) is not int or team_win not in (-1, 1) or (margin > 0 and team_win != 1) or (margin < 0 and team_win != -1):
                    raise ValueError(f"{path}:{line_number}: inconsistent candidate team_win")
                labels[index] = margin
            if selected not in labels:
                raise ValueError(f"{path}:{line_number}: selected candidate has no Q label")
            rows.append({"key": key, "state": state, "tokens": np.asarray(raw_tokens, dtype=np.int64),
                         "actions": action_array, "selected": selected, "labels": labels})
    if not rows:
        raise ValueError(f"{path}: no self-play rows")
    return rows


def batches(rows: list[dict], batch_size: int, seed: int, training: bool):
    order = np.arange(len(rows), dtype=np.int64)
    if training:
        np.random.default_rng(seed).shuffle(order)
    for begin in range(0, len(order), batch_size):
        selected = [rows[int(index)] for index in order[begin:begin + batch_size]]
        max_length = max(len(row["tokens"]) for row in selected)
        max_count = max(len(row["actions"]) for row in selected)
        tokens = np.zeros((len(selected), max_length), dtype=np.int64)
        lengths = np.zeros(len(selected), dtype=np.int64)
        state = np.stack([row["state"] for row in selected]).astype(np.float32)
        actions = np.zeros((len(selected), max_count, 128), dtype=np.float32)
        mask = np.zeros((len(selected), max_count), dtype=np.bool_)
        labels = np.full((len(selected), max_count), np.nan, dtype=np.float32)
        chosen = np.zeros(len(selected), dtype=np.int64)
        for row_index, row in enumerate(selected):
            count, length = len(row["actions"]), len(row["tokens"])
            tokens[row_index, :length] = row["tokens"]
            lengths[row_index] = length
            actions[row_index, :count] = row["actions"]
            mask[row_index, :count] = True
            chosen[row_index] = row["selected"]
            for index, margin in row["labels"].items():
                labels[row_index, index] = margin
        yield {"tokens": torch.from_numpy(tokens), "lengths": torch.from_numpy(lengths),
               "state": torch.from_numpy(state), "actions": torch.from_numpy(actions),
               "mask": torch.from_numpy(mask), "q_labels": torch.from_numpy(labels),
               "selected": torch.from_numpy(chosen)}


def rollout_pairwise_loss(scores, mask, labels, max_pairs=64, margin=0.10):
    total = scores.new_zeros((), dtype=torch.float32)
    count = correct = rows_used = 0
    for row in range(scores.shape[0]):
        valid = mask[row] & torch.isfinite(labels[row])
        indices = torch.nonzero(valid, as_tuple=False).flatten().tolist()
        pairs = [(i, j) for i in indices for j in indices if labels[row, i] > labels[row, j]]
        pairs = pairs[:max_pairs]
        if not pairs:
            continue
        left = torch.as_tensor([item[0] for item in pairs], device=scores.device)
        right = torch.as_tensor([item[1] for item in pairs], device=scores.device)
        delta = scores[row, left] - scores[row, right]
        total = total + F.softplus(margin - delta).float().sum()
        count += len(pairs); rows_used += 1; correct += int((delta > 0).sum())
    if count == 0:
        return scores.new_zeros((), dtype=torch.float32), 0, 0, 0
    return total / count, count, rows_used, correct


def q_value_loss(scores, mask, labels):
    selected = mask & torch.isfinite(labels)
    if not bool(selected.any()):
        return scores.new_zeros((), dtype=torch.float32), 0, 0.0
    # Scores are unconstrained logits; margins in [-3,3] are scaled to [-1,1].
    prediction = scores[selected].float()
    target = (labels[selected] / 3.0).float()
    loss = F.smooth_l1_loss(prediction, target)
    return loss, int(selected.sum()), float((prediction - target).abs().sum().detach())


def q_listwise_loss(scores, mask, labels, selected, beta=2.0, behavior_mix=0.25):
    """Tie-aware listwise loss over the labelled candidate subset.

    Rollout labels cover only a sampled subset of legal actions.  Restricting
    the soft target to that subset avoids treating every unlabelled legal move
    as a negative.  Equal terminal margins receive equal target probability
    (and are therefore ties rather than an arbitrary order).  ``behavior_mix``
    retains a small target mass on the fixed-policy selected action, since a
    selected action can legitimately have a lower fixed-policy margin than an
    unselected counterfactual.
    """
    if beta <= 0 or not math.isfinite(beta):
        raise ValueError("listwise beta must be finite and positive")
    if not 0 <= behavior_mix <= 1 or not math.isfinite(behavior_mix):
        raise ValueError("listwise behavior mix must be finite in [0,1]")
    total = scores.new_zeros((), dtype=torch.float32)
    rows_used = 0
    for row in range(scores.shape[0]):
        valid = mask[row] & torch.isfinite(labels[row])
        indices = torch.nonzero(valid, as_tuple=False).flatten()
        # A singleton labelled subset carries no ranking information and has
        # zero listwise NLL by construction, so leave it to BC/value losses.
        if indices.numel() < 2:
            continue
        logits = scores[row, indices].float()
        scaled = (labels[row, indices].float() / 3.0) * beta
        target = torch.softmax(scaled, dim=0)
        if behavior_mix:
            target = target * (1.0 - behavior_mix)
            selected_matches = (indices == selected[row]).nonzero(as_tuple=False).flatten()
            if selected_matches.numel() == 1:
                target[selected_matches[0]] += behavior_mix
        total = total - torch.sum(target * F.log_softmax(logits, dim=0))
        rows_used += 1
    if rows_used == 0:
        return scores.new_zeros((), dtype=torch.float32), 0
    return total / rows_used, rows_used


def evaluate(model, rows, batch_size, device, max_pairs, margin, listwise_beta=2.0):
    totals = {"rows": 0, "pairs": 0, "pair_correct": 0, "pair_rows": 0,
              "labels": 0, "value_abs_error": 0.0, "selected": 0, "selected_best": 0,
              "listwise_rows": 0, "listwise_nll": 0.0, "labelled_best": 0}
    model.eval()
    with torch.inference_mode():
        for batch in batches(rows, batch_size, 0, False):
            batch = {key: value.to(device) for key, value in batch.items()}
            q_labels, selected = batch.pop("q_labels"), batch.pop("selected")
            scores = model(**batch)
            _, pairs, pair_rows, pair_correct = rollout_pairwise_loss(scores, batch["mask"], q_labels, max_pairs, margin)
            _, labels, abs_error = q_value_loss(scores, batch["mask"], q_labels)
            listwise_loss, listwise_rows = q_listwise_loss(
                scores, batch["mask"], q_labels, selected, beta=listwise_beta, behavior_mix=0.0)
            winners = scores.argmax(-1)
            totals["rows"] += len(selected); totals["pairs"] += pairs; totals["pair_rows"] += pair_rows
            totals["pair_correct"] += pair_correct; totals["labels"] += labels; totals["value_abs_error"] += abs_error
            totals["listwise_rows"] += listwise_rows; totals["listwise_nll"] += float(listwise_loss) * listwise_rows
            totals["selected"] += int((winners == selected).sum())
            labelled = batch["mask"] & torch.isfinite(q_labels)
            best_label = torch.where(labelled, q_labels, torch.full_like(q_labels, float("-inf"))).argmax(-1)
            totals["selected_best"] += int((selected == best_label).sum())
            for row in range(scores.shape[0]):
                indices = torch.nonzero(labelled[row], as_tuple=False).flatten()
                if indices.numel() < 2:
                    continue
                max_label = q_labels[row, indices].max()
                predicted = scores[row, indices].argmax()
                totals["labelled_best"] += int((q_labels[row, indices[predicted]] == max_label).item())
    totals["pair_accuracy"] = totals["pair_correct"] / max(1, totals["pairs"])
    totals["value_mae"] = totals["value_abs_error"] / max(1, totals["labels"])
    totals["selected_accuracy"] = totals["selected"] / max(1, totals["rows"])
    totals["selected_is_q_best"] = totals["selected_best"] / max(1, totals["rows"])
    totals["listwise_nll"] = totals["listwise_nll"] / max(1, totals["listwise_rows"])
    totals["labelled_best_accuracy"] = totals["labelled_best"] / max(1, totals["listwise_rows"])
    return totals


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train", type=Path, required=True)
    parser.add_argument("--train-report", type=Path, required=True)
    parser.add_argument("--validation", type=Path, required=True)
    parser.add_argument("--validation-report", type=Path, required=True)
    parser.add_argument("--init", type=Path, default=Path("models/bc-v2-full-fp32"))
    parser.add_argument("--output", type=Path, default=Path("models/research-rollout-q-v1"))
    parser.add_argument("--epochs", type=int, default=4)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--seed", type=int, default=20261003)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--fp32", action="store_true")
    parser.add_argument("--pair-weight", type=float, default=1.0)
    parser.add_argument("--value-weight", type=float, default=0.1)
    parser.add_argument("--bc-weight", type=float, default=0.1)
    parser.add_argument("--max-pairs", type=int, default=64)
    parser.add_argument("--margin", type=float, default=0.10)
    parser.add_argument("--listwise-weight", type=float, default=0.0,
                        help="opt-in tie-aware labelled-candidate listwise Q loss")
    parser.add_argument("--listwise-beta", type=float, default=2.0,
                        help="soft-target sharpness for the opt-in listwise loss")
    parser.add_argument("--listwise-behavior-mix", type=float, default=0.25,
                        help="selected-action target mass for the opt-in listwise loss")
    args = parser.parse_args()
    if args.epochs < 1 or args.batch_size < 1 or args.max_pairs < 1:
        raise ValueError("epochs, batch-size and max-pairs must be positive")
    for value in (args.lr, args.pair_weight, args.value_weight, args.bc_weight, args.margin,
                  args.listwise_weight, args.listwise_beta, args.listwise_behavior_mix):
        if not math.isfinite(value) or value < 0 or (value == 0 and value is args.lr):
            raise ValueError("objective weights must be finite/nonnegative; learning rate must be positive")
    if args.lr <= 0:
        raise ValueError("learning rate must be positive")
    if args.listwise_beta <= 0:
        raise ValueError("listwise-beta must be positive")
    if not 0 <= args.listwise_behavior_mix <= 1:
        raise ValueError("listwise-behavior-mix must be in [0,1]")
    train_path, validation_path = args.train.resolve(), args.validation.resolve()
    train_report_path, validation_report_path = args.train_report.resolve(), args.validation_report.resolve()
    if train_path == validation_path:
        raise ValueError("train and validation rollout paths must differ")
    if (args.output / "best.pt").exists():
        raise FileExistsError("choose a new output directory; existing checkpoint is preserved")
    train_identity = report_rollout_identity(train_report_path)[:2]
    validation_identity = report_rollout_identity(validation_report_path)[:2]
    train_rows = load_rollouts(train_path, train_report_path, expected_identity=train_identity)
    if validation_identity != train_identity:
        raise ValueError("train/validation rollout identities differ")
    validation_rows = load_rollouts(validation_path, validation_report_path, expected_identity=train_identity)
    overlap = {row["key"] for row in train_rows} & {row["key"] for row in validation_rows}
    if overlap:
        raise ValueError(f"rollout leakage: {len(overlap)} duplicate row identities across train/validation")
    # A row key includes event/seat, but rows from the same deal must also be
    # kept on one side of the split.  The generator contract makes
    # ``game_seed`` the deal identity and ``(game_seed, game_index)`` the game
    # identity; reject either overlap before model state is initialized.
    train_games = {(row["key"][0], row["key"][1]) for row in train_rows}
    validation_games = {(row["key"][0], row["key"][1]) for row in validation_rows}
    game_overlap = train_games & validation_games
    if game_overlap:
        raise ValueError(f"rollout leakage: {len(game_overlap)} duplicate games across train/validation")
    train_deals = {row["key"][0] for row in train_rows}
    validation_deals = {row["key"][0] for row in validation_rows}
    deal_overlap = train_deals & validation_deals
    if deal_overlap:
        raise ValueError(f"rollout leakage: {len(deal_overlap)} duplicate game_seed/deals across train/validation")
    random.seed(args.seed); np.random.seed(args.seed); torch.manual_seed(args.seed); torch.set_num_threads(4)
    device = torch.device(args.device)
    if device.type == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA is unavailable; refusing silent CPU fallback")
        torch.cuda.manual_seed_all(args.seed); torch.backends.cuda.matmul.allow_tf32 = False
    init_path = args.init.resolve(); checkpoint_path = init_path / "best.pt" if init_path.is_dir() else init_path
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    model = CandidateModel(ModelConfig(**checkpoint.get("config", asdict(ModelConfig())))).to(device)
    model.load_state_dict(checkpoint["state_dict"])
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=.01)
    args.output.mkdir(parents=True, exist_ok=True)
    provenance = {"schema": EXPERIMENT_SCHEMA, "seed": args.seed, "train_jsonl": str(train_path),
                  "train_jsonl_sha256": sha256_file(train_path), "validation_jsonl": str(validation_path),
                  "validation_jsonl_sha256": sha256_file(validation_path), "train_report": str(train_report_path),
                  "train_report_sha256": sha256_file(train_report_path), "validation_report": str(validation_report_path),
                  "validation_report_sha256": sha256_file(validation_report_path), "train_rows": len(train_rows),
                  "train_rollout_rules_contract": train_identity[0], "train_oracle_sha256": train_identity[1],
                  "validation_rollout_rules_contract": validation_identity[0],
                  "validation_oracle_sha256": validation_identity[1],
                  "train_game_count": len(train_games), "validation_game_count": len(validation_games),
                  "train_deal_count": len(train_deals), "validation_deal_count": len(validation_deals),
                  "validation_rows": len(validation_rows), "init_checkpoint": str(checkpoint_path),
                  "init_checkpoint_sha256": sha256_file(checkpoint_path), "train_script_sha256": sha256_file(__file__),
                  "model_script_sha256": sha256_file(Path(__file__).with_name("model.py")), "torch": str(torch.__version__),
                  "device": str(device), "epochs_requested": args.epochs, "batch_size": args.batch_size,
                  "learning_rate": args.lr, "pair_weight": args.pair_weight, "value_weight": args.value_weight,
                  "bc_weight": args.bc_weight, "max_pairs": args.max_pairs, "margin": args.margin,
                  "listwise_weight": args.listwise_weight, "listwise_beta": args.listwise_beta,
                  "listwise_behavior_mix": args.listwise_behavior_mix,
                  "test_used": False, "release_artifact": False,
                  "q_definition": "fixed-policy terminal team margin from forced candidate; larger margin ranks higher"}
    initial = evaluate(model, validation_rows, args.batch_size, device, args.max_pairs, args.margin,
                       args.listwise_beta)
    report = {"status": "running", "provenance": provenance, "initial_validation": initial, "epochs": []}
    atomic_json(args.output / "training.json", report)
    print(json.dumps({"event": "initial", "validation": initial}, ensure_ascii=False), flush=True)
    best = float("inf"); started = time.monotonic(); global_step = 0; mixed = device.type == "cuda" and not args.fp32
    for epoch in range(args.epochs):
        model.train(); sums = {"pair": 0.0, "pairs": 0, "pair_correct": 0, "value": 0.0, "labels": 0,
                               "bc": 0.0, "listwise": 0.0, "listwise_rows": 0, "rows": 0}
        epoch_started = time.monotonic()
        for batch in batches(train_rows, args.batch_size, args.seed + epoch, True):
            batch = {key: value.to(device) for key, value in batch.items()}
            q_labels, selected = batch.pop("q_labels"), batch.pop("selected")
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16) if mixed else nullcontext():
                scores = model(**batch)
                pair_loss, pairs, _, pair_correct = rollout_pairwise_loss(scores, batch["mask"], q_labels, args.max_pairs, args.margin)
                value_loss, labels, _ = q_value_loss(scores, batch["mask"], q_labels)
                listwise_loss, listwise_rows = q_listwise_loss(
                    scores, batch["mask"], q_labels, selected, beta=args.listwise_beta,
                    behavior_mix=args.listwise_behavior_mix)
                # The selected action is the behavior-policy action.  This
                # term prevents tiny rollouts from drifting arbitrarily from
                # the existing BC policy while Q labels accumulate.
                bc_loss = F.cross_entropy(scores, selected)
                loss = (args.pair_weight * pair_loss + args.value_weight * value_loss
                        + args.bc_weight * bc_loss + args.listwise_weight * listwise_loss)
            if not torch.isfinite(loss):
                raise RuntimeError("nonfinite rollout-Q loss")
            loss.backward(); torch.nn.utils.clip_grad_norm_(model.parameters(), 1., error_if_nonfinite=True); optimizer.step()
            sums["pair"] += float(pair_loss.detach()) * pairs; sums["pairs"] += pairs; sums["pair_correct"] += pair_correct
            sums["value"] += float(value_loss.detach()) * labels; sums["labels"] += labels; sums["bc"] += float(bc_loss.detach()) * len(selected)
            sums["listwise"] += float(listwise_loss.detach()) * listwise_rows; sums["listwise_rows"] += listwise_rows
            sums["rows"] += len(selected); global_step += 1
        validation = evaluate(model, validation_rows, args.batch_size, device, args.max_pairs, args.margin,
                              args.listwise_beta)
        row = {"epoch": epoch + 1, "train_rows": sums["rows"], "train_pairwise": sums["pair"] / max(1, sums["pairs"]),
               "train_pair_count": sums["pairs"], "train_pair_accuracy": sums["pair_correct"] / max(1, sums["pairs"]),
               "train_value": sums["value"] / max(1, sums["labels"]), "train_bc": sums["bc"] / max(1, sums["rows"]),
               "train_listwise": sums["listwise"] / max(1, sums["listwise_rows"]),
               "train_listwise_rows": sums["listwise_rows"],
               "validation": validation, "seconds": time.monotonic() - epoch_started, "steps": global_step}
        # Select by policy-evaluation pair loss proxy (1 - accuracy) with MAE
        # tie-break; there is no release/test criterion here.
        objective = (1.0 - validation["pair_accuracy"]) + 0.05 * validation["value_mae"]
        row["selection_objective"] = objective
        if objective < best:
            best = objective
            saved = {"state_dict": {key: value.detach().cpu() for key, value in model.state_dict().items()},
                     "config": asdict(model.config), "provenance": dict(provenance, selected_epoch=epoch + 1,
                                                                          validation=validation, selection_objective=objective,
                                                                          optimizer_steps=global_step)}
            temp = args.output / "best.pt.tmp"; torch.save(saved, temp); temp.replace(args.output / "best.pt"); row["new_best"] = True
            report["best_epoch"] = epoch + 1
        report["epochs"].append(row); report["seconds"] = time.monotonic() - started; atomic_json(args.output / "training.json", report)
        print(json.dumps({"event": "epoch_done", **row}, ensure_ascii=False), flush=True)
    report["status"] = "completed"; report["checkpoint_sha256"] = sha256_file(args.output / "best.pt")
    report["peak_cuda_mebibytes"] = torch.cuda.max_memory_allocated() / 2**20 if device.type == "cuda" else None
    atomic_json(args.output / "training.json", report)
    print(json.dumps({"event": "completed", "best_epoch": report.get("best_epoch"), "selection_objective": best,
                      "seconds": report["seconds"], "checkpoint_sha256": report["checkpoint_sha256"]}, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
